"""Add semester to lesson table

Revision ID: 3fac157b030a
Revises: None
Create Date: 2016-07-07 16:29:52.646727

"""

# revision identifiers, used by Alembic.
revision = '3fac157b030a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('semester_part', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'semester_part')
    ### end Alembic commands ###
