"""Remove unnecessary relationship

Revision ID: 56700f35a9ab
Revises: 84474ea117fe
Create Date: 2016-07-07 18:22:16.448527

"""

# revision identifiers, used by Alembic.
revision = '56700f35a9ab'
down_revision = '84474ea117fe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'lesson_teacher_id_fkey', 'lesson', type_='foreignkey')
    op.drop_column('lesson', 'teacher_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'lesson_teacher_id_fkey', 'lesson', 'teacher', ['teacher_id'], ['teacher_id'])
    ### end Alembic commands ###
