"""empty message

Revision ID: 84474ea117fe
Revises: None
Create Date: 2016-07-07 17:54:41.579400

"""

# revision identifiers, used by Alembic.
revision = '84474ea117fe'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_full_name', sa.String(), nullable=True),
    sa.Column('group_url', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('institute',
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('institute_abbr', sa.String(length=10, convert_unicode=True), nullable=True),
    sa.Column('institute_full_name', sa.String(convert_unicode=True), nullable=True),
    sa.PrimaryKeyConstraint('institute_id'),
    sa.UniqueConstraint('institute_abbr')
    )
    op.create_table('teacher',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.Unicode(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('teacher_id'),
    sa.UniqueConstraint('teacher_name')
    )
    op.create_table('time',
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('time_number', sa.Integer(), nullable=True),
    sa.Column('time_start', sa.Time(), nullable=True),
    sa.Column('time_end', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('time_id'),
    sa.UniqueConstraint('time_number')
    )
    op.create_table('lesson',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('lesson_name', sa.Unicode(), nullable=True),
    sa.Column('lesson_number', sa.Integer(), nullable=True),
    sa.Column('lesson_type', sa.Unicode(), nullable=True),
    sa.Column('lesson_week', sa.Integer(), nullable=True),
    sa.Column('subgroup', sa.Integer(), nullable=True),
    sa.Column('room', sa.Unicode(), nullable=True),
    sa.Column('semester_part', sa.Integer(), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('day_name', sa.Unicode(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['time.time_id'], ),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_table('lesson_teacher',
    sa.Column('lessonteacher_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.lesson_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('lessonteacher_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_teacher')
    op.drop_table('lesson')
    op.drop_table('time')
    op.drop_table('teacher')
    op.drop_table('institute')
    op.drop_table('group')
    ### end Alembic commands ###
