"""empty message

Revision ID: c32c4f948270
Revises: 56700f35a9ab
Create Date: 2016-07-07 22:04:33.907571

"""

# revision identifiers, used by Alembic.
revision = 'c32c4f948270'
down_revision = '56700f35a9ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('institute_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group', 'institute', ['institute_id'], ['institute_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'institute_id')
    ### end Alembic commands ###
